language: java
jdk:
  - openjdk8

branches:
  only:
    - master

notifications:
  slack:
    secure: XCXuCVYhOZUjheto1V3PBOMR2aenbnnq2loErv32Vam3XefRYA3e5P4iMkWBvZXirAAB8oWo/nWnbA4rby5wJbbfSRYLdH0yQ9thGkztDkmC6y14qPSYOCb+WqKUZ5f3WPq0yYJFYavzfd/VwFz4CHhs79JA4S2rQwQ4otfKSqJ6A04eOcw1F4lfCFuB8GdqMnYet5R0I6KllbmW7goZ8Y1xwu6c/yheP4jNza06P8BDLhifLnW9CD1K6id0T/1NZRoSngr/aaXVojnffGRd1UKA3WqKD2mmpPF9vkjl79UpT9t30AJKZKowa7DxH25PFq5byJ4tvlY3NJVgcjGCyTV/AVWV4Td2ch/1eE4v3KOHjf3DUEdIro1yhOOPrqm+EzADicKZCTEnYrmM5fjkVz1mw9lB65tyRAbbawqR+W63PdrkjjEUi3PZmg7HeQjf0eLVeJ0oM2jaw4/0rrewE7q4TZ9pHbnSzdpwjC8oJEC1tZYrJ1leUWFe4as8dnXTr15ZFbM60KUtkHu7AygKxI+e2wXZz32tBbJSoffHynOLytXJSP8Xuzgu656BgfuFcDKK8A387L6vp3R4u3nS8ZyqYIqYjUInEA2QEfAxCTRkyMcX2uPNl0LS68oBjpGF6SIWqAPJ9poE6AQXcavPFmKo2RwtC2PvJFqlBBvvVzU=
